[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg"]

[phases.build]
cmds = ["npm ci", "npx prisma generate", "npx prisma db push --accept-data-loss", "npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
RAILWAY_VOLUME_MOUNT_PATH = "/data"
RAILWAY_ENVIRONMENT = "production"