[build]
builder = "railpack"
buildCommand = "npx prisma generate && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[mounts]]
source = "uploads-volume"
target = "/data"

[variables]
NODE_ENV = "production"
RAILWAY_VOLUME_MOUNT_PATH = "/data"
RAILWAY_ENVIRONMENT = "production"
NEXT_TELEMETRY_DISABLED = "1"