[phases.setup]
nixpkgs = ["nodejs_22", "npm"]
workingDirectory = "ai-model-gallery"

[phases.install]
cmd = "cd ai-model-gallery && npm install --production=false"

[phases.build]
cmd = "cd ai-model-gallery && npm run build"

[start]
cmd = "cd ai-model-gallery && npm run start"

[variables]
NODE_ENV = "production"